Don't use pragma inside a function, it breaks compiling with older GCCs.
XKBBind.c:230: error: #pragma GCC diagnostic not allowed inside functions

Signed-off-by: Thomas Klausner <wiz@gatalith.at>